---
# Inventory/hosts.yml
#
# The list of servers which make up the cluster.  This setup is for the
# controller role where we will setup kubespray on a remote host and deploy from
# there.  Setting up a sort of bastion and with faster transfer speeds.

all:
    hosts:
        optimusPrime: 
            ansible_host: 159.65.241.162
        master-0: 
            ansible_host: 172.18.74.67
        worker-1:  
            ansible_host: 172.18.66.69
        worker-0:   
            ansible_host: 172.18.79.229
    vars:
        ansible_connection: ssh
        ansible_python_interpreter: /usr/bin/python3
        ansible_user: root
        ansible_port: 22
    children:
        controller:
            hosts:
                optimusPrime: {}
        cluster:
            hosts:
                master-0: {}
                worker-0: {}
                worker-1: {}
        masters:
            hosts:
                master-0: {}

                
