---
# controller-prep.yml
# Run this playbook to set up a contoller node that will issue commands to the
# associated kubernetes cluster
#
# Assumptions:
# Fresh-box.yml has been run to update cache and upgrade packages
# Remote host is Fedora, CentOS, or REHL
#
# Variables:
# `release_branch`: branch/release of kubespray to use. Default: release-2.12
# `cluster_name`: arbitrary name for your cluster to be used in folder
#                    structure on the controller. Default: mycluster
#
# Example invocation:
# ansible-playbook -i inventory/hosts.yml playbooks/controller/controller-prep.yml
#
# ansible-playbook -i inventory/hosts.yml playbooks/controller/controller-prep.yml \
#                  -e release_branch=release-2.10 \
#                  -e cluster_name=ml_cluster

- name: Enusre required packages are present 
  yum:
      name: ['python3-pip', 'git', 'curl', 'gnupg2']
      state: present

- name: Upgrade Pip
  pip:
      name: pip 
      executable: pip3
      extra_args: "--upgrade"

- name: Clone Kubespray Repo
  git:
      repo: 'https://github.com/kubernetes-sigs/kubespray.git'
      dest: "{{ ansible_env.HOME }}/kubespray"
      version: '{{ release_branch }}'

- name: Install Required Packages
  pip:
      requirements: "{{ ansible_env.HOME }}/kubespray/requirements.txt"
      executable: pip3

- name: Check Cryptography Version
  pip:
      executable: pip3
      name: 
       - cryptography>=2.5  

- name: Copy Inventory Folder
  copy:
      src: "{{ ansible_env.HOME }}/kubespray/inventory/sample/"
      dest: "{{ ansible_env.HOME }}/kubespray/inventory/{{ cluster_name }}"
      remote_src: yes

- name: Ensure Hosts File Does Not Exist
  file:
      path: "{{ ansible_env.HOME }}/kubespray/inventory/{{ cluster_name }}/hosts.yml"
      state: absent

- name: Generate Inventory File Contents
  command: 
      cmd: python3 contrib/inventory_builder/inventory.py {{ cluster_nodes_ips }}
      chdir: "{{ ansible_env.HOME }}/kubespray"
  environment: 
      CONFIG_FILE: "{{ ansible_env.HOME }}/kubespray/inventory/{{ cluster_name }}/hosts.yml"

- name: Add my specific requirenments for connection to cluster
  blockinfile:
      path: "{{ ansible_env.HOME }}/kubespray/inventory/{{ cluster_name }}/group_vars/all/all.yml"
      block: |
          ansible_user: "{{ deploy_user }}"
          ansible_connection: ssh
          ansible_python_interpreter: /usr/bin/python3

- name: Update Kubespray to get Kubectl
  lineinfile:
      path: "{{ ansible_env.HOME }}/kubespray/inventory/mycluster/group_vars/k8s-cluster/k8s-cluster.yml"
      regexp: 'kubectl_localhost:'
      line: 'kubectl_localhost: true'

- name: Update Kubespray to retrieve admin.conf
  lineinfile:
      path: "{{ ansible_env.HOME }}/kubespray/inventory/mycluster/group_vars/k8s-cluster/k8s-cluster.yml"
      regexp: 'kubeconfig_localhost:'
      line: 'kubeconfig_localhost: true'

- name: Generate SSH key
  openssh_keypair:
    path: "{{ ansible_env.HOME }}/.ssh/id_rsa"
    mode: 0600

- name: Fetch Public key
  fetch:
      src: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"
      dest: "/tmp/ctl-id_rsa.pub"
      flat: yes

